#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    token-overhaul-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^token-overhaul\.ddev\.site$`)
      
      service: "token-overhaul-web-80"
      tls: false
      # middlewares:
      #   - "token-overhaul-redirectHttps"
    token-overhaul-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^token-overhaul\.ddev\.site$`)
      
      service: "token-overhaul-web-8025"
      tls: false
      # middlewares:
      #   - "token-overhaul-redirectHttps"
    token-overhaul-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^token-overhaul\.ddev\.site$`)
      
      service: "token-overhaul-xhgui-80"
      tls: false
      # middlewares:
      #   - "token-overhaul-redirectHttps"
    token-overhaul-selenium-chrome-7900-http:
      entrypoints:
        - http-7910
      rule: HostRegexp(`^token-overhaul\.ddev\.site$`)
      
      service: "token-overhaul-selenium-chrome-7900"
      tls: false
      # middlewares:
      #   - "token-overhaul-redirectHttps"
    
    
    
    token-overhaul-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^token-overhaul\.ddev\.site$`)
      
      service: "token-overhaul-web-80"
      
      tls: true
      
    token-overhaul-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^token-overhaul\.ddev\.site$`)
      
      service: "token-overhaul-web-8025"
      
      tls: true
      
    
    token-overhaul-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^token-overhaul\.ddev\.site$`)
      
      service: "token-overhaul-xhgui-80"
      
      tls: true
      
    
    token-overhaul-selenium-chrome-7900-https:
      entrypoints:
        - http-7900
      rule: HostRegexp(`^token-overhaul\.ddev\.site$`)
      
      service: "token-overhaul-selenium-chrome-7900"
      
      tls: true
      
    

  middlewares:
    token-overhaul-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    token-overhaul-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-token-overhaul-web:80
        
    token-overhaul-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-token-overhaul-web:8025
        
    
    
    token-overhaul-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-token-overhaul-xhgui:80
        
    
    token-overhaul-selenium-chrome-7900:
      loadbalancer:
        servers:
          - url: http://ddev-token-overhaul-selenium-chrome:7900
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/token-overhaul.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/token-overhaul.key